### ISSUE TITLE
[nvim_set_client_info] no...m_rpc_methods.py

### ISSUE THREAD

**Issue by grininmonkey** [roxma/vim-hug-neovim-rpc#61] opened 2019-11-16 13:09 UTC
I am on Arch, and a few days ago after a huge list of python-[X] packages popped up in an update I started receiving the following error in vim when going into insert mode .. ( no errors on launch )

`[vim-hug-neovim-rpc] rpc method [nvim_set_client_info] no...m_rpc_methods.py. Please send PR or contact the mantainer`

I have re-performed the install/setup process I originally did but has no impact... figure I would try and ask here while I continue to scratch my head and figure it out ;-)

**Comment by Shougo** [comment] 2019-11-16 13:35
I think you need to rebuild your Vim.

**Comment by grininmonkey** [comment] 2019-11-16 14:56
I install vim via my package manager... but I noticed it seems to actually be working.. just has the error message on initial insert .... [quick peek](https://imgur.com/a/bdTW7yn)

**Comment by zhmars** [comment] 2019-11-18 05:48
I had the same issue today on Arch Linux after updating to python-pynvim 0.4.0.

A simple workaround is  downgrading python-pynvim to 0.3.2.

**Comment by FatBoyXPC** [comment] 2019-11-18 20:30
I have the same issue.

**Comment by vp1981** [comment] 2019-11-19 00:06
Hello,
same here, but this is expected:
https://github.com/neovim/pynvim/commit/a5ee340d10f8d574ddb45537a2cc1491badd3b89

> - 6310063 session: set client info (not only for host)

**Comment by grininmonkey** [comment] 2019-11-19 03:04
Yeah... that seemed to work for me... (for arch).. I uninstalled pynvim greenlet... pacman'ed python-greenlet and then pip'ed pynvim==0.3.2 ...... no errors now ;-)

**Comment by Shougo** [comment] 2019-11-19 03:10
Reproduced for me.
I get the reason.
I will fix it later.  Please wait.

**Comment by Shougo** [comment] 2019-11-19 23:13
I have created the PR.
Please test until it is merged.

**Closed as completed** 2019-11-20 01:55 UTC
